[project]
name = "master-thesis"
version = "0.1.0"
description = "Trophoblast Organoid Atlas"
requires-python = ">=3.13"
dependencies = [
    "disutils>=1.4.32.post2",
    "pyyaml>=6.0.3",
    "scanorama>=1.7.4",
    "scanpy>=1.11.5",
    "scib>=1.1.7",
    "scikit-misc>=0.5.2",
    "scmappy>=0.2",
    "scvi>=0.6.8",
    "scvi-tools>=1.4.0.post1",
    "setuptools>=80.9.0",
]

[tool.uv.sources]
scmappy = { git = "https://github.com/gatocor/scmappy.git", rev = "affa0c378ad274e27279f60c48a58644f01a8772" }
